# 2-1,张量数据结构

程序 = 数据结构+算法。

TensorFlow 程序 = 张量数据结构 + 计算图算法语言

张量和计算图是 TensorFlow 的核心概念。

Tensorflow 的基本数据结构是张量 Tensor。张量即多维数组。Tensorflow 的张量和 numpy 中的 array 很类似。

从行为特性来看，有两种类型的张量，常量 constant 和变量 Variable.

常量的值在计算图中不可以被重新赋值，变量可以在计算图中用 assign 等算子重新赋值。

### 一，常量张量

张量的数据类型和 `numpy.array` 基本一一对应。

In [1]:
%load_ext nb_black

<IPython.core.display.Javascript object>

In [2]:
import numpy as np
import tensorflow as tf

i = tf.constant(1)  # tf.int32
l = tf.constant(1, dtype=tf.int64)  # tf.int64
f = tf.constant(1.23)  # tf.float32
d = tf.constant(3.14, dtype=tf.float64)  # tf.float64
s = tf.constant("hello world")  # tf.string
b = tf.constant(True)  # tf.bool

print(tf.int64 == np.int64)
print(tf.bool == np.bool_)
print(tf.double == np.float64)
print(tf.string == np.unicode)  # tf.string 和 np.unicode 类型不等价

True
True
True
False


/tmp/ipykernel_19932/2298629636.py:14: DeprecationWarning: `np.unicode` is a deprecated alias for `np.compat.unicode`. To silence this warning, use `np.compat.unicode` by itself. In the likely event your code does not need to work on Python 2 you can use the builtin `str` for which `np.compat.unicode` is itself an alias. Doing this will not modify any behaviour and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  print(tf.string == np.unicode)  # tf.string 和 np.unicode 类型不等价


<IPython.core.display.Javascript object>

不同类型的数据可以用不同维度 (rank) 的张量来表示。

标量为 0 维张量，向量为 1 维张量，矩阵为 2 维张量。

彩色图像有 rgb 三个通道，可以表示为 3 维张量。

视频还有时间维，可以表示为4维张量。

可以简单地总结为：有几层中括号，就是多少维的张量。

In [3]:
scalar = tf.constant(True)  # 标量，0 维张量

print(tf.rank(scalar))
print(scalar.numpy().ndim)

tf.Tensor(0, shape=(), dtype=int32)
0


<IPython.core.display.Javascript object>

In [4]:
vector = tf.constant([1.0, 2.0, 3.0])  # 向量，1 维张量

print(tf.rank(vector))
print(np.ndim(vector.numpy()))

tf.Tensor(1, shape=(), dtype=int32)
1


<IPython.core.display.Javascript object>

In [5]:
matrix = tf.constant([[1.0, 2.0], [3.0, 4.0]])  # 矩阵，2 维张量

print(tf.rank(matrix).numpy())
print(np.ndim(matrix))

2
2


<IPython.core.display.Javascript object>

In [6]:
tensor_3 = tf.constant([[[1.0, 2.0], [3.0, 4.0]], [[5.0, 6.0], [7.0, 8.0]]])  # 3 维张量

print(tensor_3)
print(tf.rank(tensor_3))

tf.Tensor(
[[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]], shape=(2, 2, 2), dtype=float32)
tf.Tensor(3, shape=(), dtype=int32)


<IPython.core.display.Javascript object>

In [7]:
tensor_4 = tf.constant(
    [
        [[[1.0, 2.0], [3.0, 4.0]], [[5.0, 6.0], [7.0, 8.0]]],
        [[[9.0, 10.0], [11.0, 12.0]], [[13.0, 14.0], [15.0, 16.0]]],
    ]
)  # 4 维张量
print(tensor_4)
print(tf.rank(tensor_4))

tf.Tensor(
[[[[ 1.  2.]
   [ 3.  4.]]

  [[ 5.  6.]
   [ 7.  8.]]]


 [[[ 9. 10.]
   [11. 12.]]

  [[13. 14.]
   [15. 16.]]]], shape=(2, 2, 2, 2), dtype=float32)
tf.Tensor(4, shape=(), dtype=int32)


<IPython.core.display.Javascript object>

可以用 tf.cast 改变张量的数据类型。

可以用 numpy 方法将 tensorflow 中的张量转化成 numpy 中的张量。

可以用 shape 方法查看张量的尺寸。

In [8]:
h = tf.constant([123, 456], dtype=tf.int32)
f = tf.cast(h, tf.float32)
print(h.dtype, f.dtype)

<dtype: 'int32'> <dtype: 'float32'>


<IPython.core.display.Javascript object>

In [9]:
y = tf.constant([[1.0, 2.0], [3.0, 4.0]])
print(y.numpy())
print(y.shape)

[[1. 2.]
 [3. 4.]]
(2, 2)


<IPython.core.display.Javascript object>

In [10]:
u = tf.constant(u"你好，世界")
print(u.numpy())
print(u.numpy().decode("utf-8"))


b'\xe4\xbd\xa0\xe5\xa5\xbd\xef\xbc\x8c\xe4\xb8\x96\xe7\x95\x8c'
你好，世界


<IPython.core.display.Javascript object>

### 二，变量张量

模型中需要被训练的参数一般被设置成变量。

In [11]:
# 常量值不可以改变，常量的重新赋值相当于创造新的内存空间
c = tf.constant([1.0, 2.0])
print(c)
print(id(c))
c = c + tf.constant([1.0, 1.0])
print(c)
print(id(c))

tf.Tensor([1. 2.], shape=(2,), dtype=float32)
140023718815696
tf.Tensor([2. 3.], shape=(2,), dtype=float32)
140023718816400


<IPython.core.display.Javascript object>

In [13]:
# 变量的值可以改变，可以通过 assign, assign_add 等方法给变量重新赋值
v = tf.Variable([1.0, 2.0], name="v")
print(v)
print(id(v))
v.assign_add([1.0, 1.0])
print(v)
print(id(v))

<tf.Variable 'v:0' shape=(2,) dtype=float32, numpy=array([1., 2.], dtype=float32)>
140023450609792
<tf.Variable 'v:0' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)>
140023450609792


<IPython.core.display.Javascript object>